[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mi_grupo_de_whatsapp"
version = "0.0.1"
description = "Pr\u00e1ctica de clase"
authors = [
  { name = "Manuel Fco. Valenzuela Maldonado" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "ipython",
    "jupyterlab",
    "matplotlib",
    "mkdocs",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
]
requires-python = "~=3.14.0"


[tool.ruff]
line-length = 99
src = ["mi_grupo_de_whatsapp"]
include = ["pyproject.toml", "mi_grupo_de_whatsapp/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["mi_grupo_de_whatsapp"]
force-sort-within-sections = true

